# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trojan_diffusion_seminar_',
                'doc_host': 'https://akansh12.github.io',
                'git_url': 'https://github.com/akansh12/trojan_diffusion_seminar_',
                'lib_path': 'trojan_diffusion_seminar_'},
  'syms': { 'trojan_diffusion_seminar_.core': { 'trojan_diffusion_seminar_.core.foo': ( 'core.html#foo',
                                                                                        'trojan_diffusion_seminar_/core.py')},
            'trojan_diffusion_seminar_.models': {},
            'trojan_diffusion_seminar_.trojan_attack_MNIST': {},
            'trojan_diffusion_seminar_.trojan_attack_MNIST_utils': {}}}
