# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_trojan_attack_MNIST.ipynb.

# %% auto 0
__all__ = ['transform', 'train_dataset', 'test_dataset', 'train_loader', 'test_loader']

# %% ../nbs/00_trojan_attack_MNIST.ipynb 6
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = torchvision.datasets.MNIST(root='../data', train=True, transform=transform, download=True)
test_dataset = torchvision.datasets.MNIST(root='../data', train=False, transform=transform, download=True)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=512, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=512, shuffle=False)
